# Data Cleaning 
Reference: [[1](https://realpython.com/python-data-cleaning-numpy-pandas/)]

### Contents:
0. Loading Data
1. Dropping, Adding Columns
2. Indexing
3. Finding/Removing NAs and Duplicates
4. Cleaning Text with regex 
5. Cleaning an entire dataset with `applymap()`

## Loading Data
Functions:
- array, arange, linspace
- random.seed, random.random, ones, zeroes
- pd.DataFrame from np.array 
- to_csv, read_csv ; set index = False
- dtypes, index, columns, items, describe 

In [1]:
import pandas as pd
import numpy as np

In [7]:
## Raw, hard-coded data into numpy array 

# supply a list of numbers to convert into an array 
a = np.array([1,2,3,4,5,6])
print(a, end="\r\n\n")

# supply start, stop and step to get an array
b = np.arange(1,10,2)
print(b, end="\r\n\n")

# supply a start, stop and number of elements to get an array of equally spaced elements
c = np.linspace(1,10,7)
print(c)

[1 2 3 4 5 6]

[1 3 5 7 9]

[ 1.   2.5  4.   5.5  7.   8.5 10. ]


In [30]:
## Random number generator into numpy array 

# Remember to set the seed if you want it to be replicable.
np.random.seed(2019)

rnums = np.random.random([5,5]) # random numbers
r0 = np.zeros([2,2]) # fill with zeroes
r1 = np.ones([3,3]) # fill with ones
print(rnums,"\n\n", r0,"\n\n",r1)

[[0.90348221 0.39308051 0.62396996 0.6378774  0.88049907]
 [0.29917202 0.70219827 0.90320616 0.88138193 0.4057498 ]
 [0.45244662 0.26707032 0.16286487 0.8892147  0.14847623]
 [0.98472349 0.03236122 0.51535075 0.20112905 0.88601087]
 [0.51361992 0.57830159 0.29928265 0.8371974  0.52664983]] 

 [[0. 0.]
 [0. 0.]] 

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [52]:
# numpy array to pandas dataframe
data = pd.DataFrame(rnums) # convert np array to dataframe 

# rename all columns 
data.columns = ['A', 'B', 'C', 'D', 'E']
print(data)
print()

# rename a single column
data.rename(columns={'A':'Column A'}, inplace=True)
print(data)

          A         B         C         D         E
0  0.903482  0.393081  0.623970  0.637877  0.880499
1  0.299172  0.702198  0.903206  0.881382  0.405750
2  0.452447  0.267070  0.162865  0.889215  0.148476
3  0.984723  0.032361  0.515351  0.201129  0.886011
4  0.513620  0.578302  0.299283  0.837197  0.526650

   Column A         B         C         D         E
0  0.903482  0.393081  0.623970  0.637877  0.880499
1  0.299172  0.702198  0.903206  0.881382  0.405750
2  0.452447  0.267070  0.162865  0.889215  0.148476
3  0.984723  0.032361  0.515351  0.201129  0.886011
4  0.513620  0.578302  0.299283  0.837197  0.526650


In [54]:
## Writing data frame to a file (e.g. csv)
data.to_csv("data.csv",index=False)

In [121]:
## Reading from an external file 
data = pd.read_csv("data.csv")
print(data.dtypes, "\n\n", data.index, "\n\n", data.columns, "\n\n", data.items)

Column A    float64
B           float64
C           float64
D           float64
E           float64
dtype: object 

 RangeIndex(start=0, stop=5, step=1) 

 Index(['Column A', 'B', 'C', 'D', 'E'], dtype='object') 

 <bound method DataFrame.iteritems of    Column A         B         C         D         E
0  0.903482  0.393081  0.623970  0.637877  0.880499
1  0.299172  0.702198  0.903206  0.881382  0.405750
2  0.452447  0.267070  0.162865  0.889215  0.148476
3  0.984723  0.032361  0.515351  0.201129  0.886011
4  0.513620  0.578302  0.299283  0.837197  0.526650>


In [122]:
data.describe()

Column A         B         C         D         E
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean   0.630689  0.394602  0.500935  0.689360  0.569477
std    0.297966  0.262605  0.288150  0.291415  0.317337
min    0.299172  0.032361  0.162865  0.201129  0.148476
25%    0.452447  0.267070  0.299283  0.637877  0.405750
50%    0.513620  0.393081  0.515351  0.837197  0.526650
75%    0.903482  0.578302  0.623970  0.881382  0.880499
max    0.984723  0.702198  0.903206  0.889215  0.886011

## Dropping Columns 
When columns are not useful for the analysis, remove them to save space.

In [123]:
#before
data

Column A         B         C         D         E
0  0.903482  0.393081  0.623970  0.637877  0.880499
1  0.299172  0.702198  0.903206  0.881382  0.405750
2  0.452447  0.267070  0.162865  0.889215  0.148476
3  0.984723  0.032361  0.515351  0.201129  0.886011
4  0.513620  0.578302  0.299283  0.837197  0.526650

In [124]:
#after
to_drop = ['B', 'C']
data.drop(to_drop, inplace=True, axis=1)
data

Column A         D         E
0  0.903482  0.637877  0.880499
1  0.299172  0.881382  0.405750
2  0.452447  0.889215  0.148476
3  0.984723  0.201129  0.886011
4  0.513620  0.837197  0.526650

In [125]:
# OR 
data.drop(columns = 'Column A', inplace=True) # instead of only giving the name and specifying the axis
data

D         E
0  0.637877  0.880499
1  0.881382  0.405750
2  0.889215  0.148476
3  0.201129  0.886011
4  0.837197  0.526650

## Adding columns
- By directly using a new column name and specifying the new values 
- By the insert() function.

In [126]:
# Adding directly at the end by using a new name
data['G'] = np.array([3]*len(data))
data

D         E  G
0  0.637877  0.880499  3
1  0.881382  0.405750  3
2  0.889215  0.148476  3
3  0.201129  0.886011  3
4  0.837197  0.526650  3

In [127]:
# Adding at specific position
data.insert(2, "F", np.linspace(2,10,len(data)), allow_duplicates=True)
data

D         E     F  G
0  0.637877  0.880499   2.0  3
1  0.881382  0.405750   4.0  3
2  0.889215  0.148476   6.0  3
3  0.201129  0.886011   8.0  3
4  0.837197  0.526650  10.0  3

## Indexing
- Changing the Index: set_index()
- Slicing the data: loc, iloc
- Filtering
- get_dtype_counts()

In [128]:
#checking if our columns areunique 
for col in data.columns:
    print("Column {} {}".format(col, "is unique" if data[col].is_unique else "has duplicates"))

Column D is unique
Column E is unique
Column F is unique
Column G has duplicates


In [129]:
data = data.set_index('F') # Note: pandas index doesn't guarantee uniqueness, unlike SQL primary keys.
data

D         E  G
F                          
2.0   0.637877  0.880499  3
4.0   0.881382  0.405750  3
6.0   0.889215  0.148476  3
8.0   0.201129  0.886011  3
10.0  0.837197  0.526650  3

In [130]:
# Slicing the data
data.loc[:,'D'] # by column NAME

F
2.0     0.637877
4.0     0.881382
6.0     0.889215
8.0     0.201129
10.0    0.837197
Name: D, dtype: float64

In [131]:
data.iloc[:,[0,1]] # by index number of the columns

D         E
F                       
2.0   0.637877  0.880499
4.0   0.881382  0.405750
6.0   0.889215  0.148476
8.0   0.201129  0.886011
10.0  0.837197  0.526650

In [132]:
data.loc[2] # returns entire row of index = 2 (all columns)

D    0.637877
E    0.880499
G    3.000000
Name: 2.0, dtype: float64

In [133]:
data.iloc[2,1] # returns row index = 2, column index = 1 

0.1484762258202882

In [134]:
#filtering the data
data[data.D > 0.8]

D         E  G
F                          
4.0   0.881382  0.405750  3
6.0   0.889215  0.148476  3
10.0  0.837197  0.526650  3

In [135]:
data.get_dtype_counts() # returns the count of each dtype for all the columns. 

float64    2
int64      1
dtype: int64

In [137]:
# Convert datatype (to_numeric)

## Check for NA/Null

In [139]:
# Check number of nulls 
data.isnull().sum()

D    0
E    0
G    0
dtype: int64

In [140]:
data.isna().sum()

D    0
E    0
G    0
dtype: int64

Use `np.where()` to filter based on a specific condition. <br>
first arg returns a boolean, second arg = then, third arg = else. <br>
Can nest wheres in the else if needed. 

In [164]:
data.D = np.where(data.D > 0.8, 0.9, 0.7)
data

D         E  G
F                     
2.0   0.7  0.880499  3
4.0   0.9  0.405750  3
6.0   0.9  0.148476  3
8.0   0.7  0.886011  3
10.0  0.9  0.526650  3

## Removing Duplicates
Sometimes we want to pull duplicates out to check, other times we just want to drop them.

Reference: [[2](http://www.datasciencemadesimple.com/find-duplicate-rows-dataframe-python-pandas/)]

In [209]:
# create a new dataset 
d = {
    'Name':['Alisa','Bobby','jodha','jack','raghu','Cathrine',
            'Alisa','Bobby','kumar','Alisa','Alex','Cathrine'],
    'Age':[26,24,23,22,23,24,26,24,22,23,24,24],
      
       'Score':[85,63,55,74,31,77,85,63,42,62,89,77]}
 
df = pd.DataFrame(d,columns=['Name','Age','Score'])
df

Name  Age  Score
0      Alisa   26     85
1      Bobby   24     63
2      jodha   23     55
3       jack   22     74
4      raghu   23     31
5   Cathrine   24     77
6      Alisa   26     85
7      Bobby   24     63
8      kumar   22     42
9      Alisa   23     62
10      Alex   24     89
11  Cathrine   24     77

In [211]:
dups = df.duplicated() # these are complete duplicates (across all the columns)
df[dups]

Name  Age  Score
6      Alisa   26     85
7      Bobby   24     63
11  Cathrine   24     77

In [215]:
# to remove the duplicates
df = df.drop_duplicates()
df

Name  Age  Score
0      Alisa   26     85
1      Bobby   24     63
2      jodha   23     55
3       jack   22     74
4      raghu   23     31
5   Cathrine   24     77
8      kumar   22     42
9      Alisa   23     62
10      Alex   24     89

### Cleaning Text
- Regex
- Filtering based on patterns (str.contains)
- Slicing a string (str[:])

In [165]:
# Let's add some strings to the dataset... 
data['H'] = ['Pig','Dog','Cat','Ant','Rat']
data['I'] = ['21st Century','20th','19','21st','19th']
data

D         E  G    H             I
F                                        
2.0   0.7  0.880499  3  Pig  21st Century
4.0   0.9  0.405750  3  Dog          20th
6.0   0.9  0.148476  3  Cat          1990
8.0   0.7  0.886011  3  Ant          21st
10.0  0.9  0.526650  3  Rat          19th

In [177]:
# Return rows which the string contains a specified regex pattern
pattern = "t$" # ends with small letter t 
data[data['H'].str.contains(pattern)]

D         E  G    H     I
F                                
6.0   0.9  0.148476  3  Cat  1990
8.0   0.7  0.886011  3  Ant  21st
10.0  0.9  0.526650  3  Rat  19th

In [182]:
# Slicing the first 2 characters from the strings in the column I : 
data.I = data.I.str[:2]
data

D         E  G    H   I
F                              
2.0   0.7  0.880499  3  Pig  21
4.0   0.9  0.405750  3  Dog  20
6.0   0.9  0.148476  3  Cat  19
8.0   0.7  0.886011  3  Ant  21
10.0  0.9  0.526650  3  Rat  19

In [187]:
data[data['H'].str.contains('[Aa]')]

D         E  G    H   I
F                              
6.0   0.9  0.148476  3  Cat  19
8.0   0.7  0.886011  3  Ant  21
10.0  0.9  0.526650  3  Rat  19

### Cleaning an entire dataset
Using the `applymap()` function, we can apply a user-defined function across all the elements of a DataFrame. 

We will use another dataset (`universty_towns`) for this.

In [192]:
utown = pd.read_csv('university_towns.txt', sep='\n', header=None)
utown.head(20)

0
0                                       Alabama[edit]
1                       Auburn (Auburn University)[1]
2              Florence (University of North Alabama)
3     Jacksonville (Jacksonville State University)[2]
4          Livingston (University of West Alabama)[2]
5            Montevallo (University of Montevallo)[2]
6                           Troy (Troy University)[2]
7   Tuscaloosa (University of Alabama, Stillman Co...
8                   Tuskegee (Tuskegee University)[5]
9                                        Alaska[edit]
10      Fairbanks (University of Alaska Fairbanks)[2]
11                                      Arizona[edit]
12         Flagstaff (Northern Arizona University)[6]
13                   Tempe (Arizona State University)
14                     Tucson (University of Arizona)
15                                     Arkansas[edit]
16  Arkadelphia (Henderson State University, Ouach...
17  Conway (Central Baptist College, Hendrix Colle...
18           Fayetteville (University of Arkansas)[7]
19           Jonesboro (Arkansas State University)[8]

The dataset is a bit dirtier. We can see the the state names are followed by the `'[edit]'` tag, and each city in the state is listed in the next few rows until the next state. 

We can read this into a list of (state, city) tuples and wrap that in a DataFrame. 

In [193]:
university_towns = []
with open('university_towns.txt') as file:
     for line in file:
         if '[edit]' in line:
             # Remember this `state` until the next is found
            state = line
         else:
             # Otherwise, we have a city; keep `state` as last-seen
             university_towns.append((state, line))
            
university_towns

[('Alabama[edit]\n', 'Auburn (Auburn University)[1]\n'),
 ('Alabama[edit]\n', 'Florence (University of North Alabama)\n'),
 ('Alabama[edit]\n', 'Jacksonville (Jacksonville State University)[2]\n'),
 ('Alabama[edit]\n', 'Livingston (University of West Alabama)[2]\n'),
 ('Alabama[edit]\n', 'Montevallo (University of Montevallo)[2]\n'),
 ('Alabama[edit]\n', 'Troy (Troy University)[2]\n'),
 ('Alabama[edit]\n',
  'Tuscaloosa (University of Alabama, Stillman College, Shelton State)[3][4]\n'),
 ('Alabama[edit]\n', 'Tuskegee (Tuskegee University)[5]\n'),
 ('Alaska[edit]\n', 'Fairbanks (University of Alaska Fairbanks)[2]\n'),
 ('Arizona[edit]\n', 'Flagstaff (Northern Arizona University)[6]\n'),
 ('Arizona[edit]\n', 'Tempe (Arizona State University)\n'),
 ('Arizona[edit]\n', 'Tucson (University of Arizona)\n'),
 ('Arkansas[edit]\n',
  'Arkadelphia (Henderson State University, Ouachita Baptist University)[2]\n'),
 ('Arkansas[edit]\n',
  'Conway (Central Baptist College, Hendrix College, Universit

In [196]:
utown = pd.DataFrame(university_towns,
                     columns=['State', 'RegionName'])
utown.head(20)

State                                         RegionName
0    Alabama[edit]\n                    Auburn (Auburn University)[1]\n
1    Alabama[edit]\n           Florence (University of North Alabama)\n
2    Alabama[edit]\n  Jacksonville (Jacksonville State University)[2]\n
3    Alabama[edit]\n       Livingston (University of West Alabama)[2]\n
4    Alabama[edit]\n         Montevallo (University of Montevallo)[2]\n
5    Alabama[edit]\n                        Troy (Troy University)[2]\n
6    Alabama[edit]\n  Tuscaloosa (University of Alabama, Stillman Co...
7    Alabama[edit]\n                Tuskegee (Tuskegee University)[5]\n
8     Alaska[edit]\n    Fairbanks (University of Alaska Fairbanks)[2]\n
9    Arizona[edit]\n       Flagstaff (Northern Arizona University)[6]\n
10   Arizona[edit]\n                 Tempe (Arizona State University)\n
11   Arizona[edit]\n                   Tucson (University of Arizona)\n
12  Arkansas[edit]\n  Arkadelphia (Henderson State University, Ouach...
13  Arkansas[edit]\n  Conway (Central Baptist College, Hendrix Colle...
14  Arkansas[edit]\n         Fayetteville (University of Arkansas)[7]\n
15  Arkansas[edit]\n         Jonesboro (Arkansas State University)[8]\n
16  Arkansas[edit]\n       Magnolia (Southern Arkansas University)[2]\n
17  Arkansas[edit]\n  Monticello (University of Arkansas at Monticel...
18  Arkansas[edit]\n       Russellville (Arkansas Tech University)[2]\n
19  Arkansas[edit]\n                   Searcy (Harding University)[5]\n

In [207]:
#define a function to get the city/state of each cell
def get_citystate(item):
    if ' (' in item:
        return item[:item.find(' (')]
    elif '[' in item:
        return item[:item.find('[')]
    else:
        return item

In [208]:
utown = utown.applymap(get_citystate)
utown.head(20)

State    RegionName
0    Alabama        Auburn
1    Alabama      Florence
2    Alabama  Jacksonville
3    Alabama    Livingston
4    Alabama    Montevallo
5    Alabama          Troy
6    Alabama    Tuscaloosa
7    Alabama      Tuskegee
8     Alaska     Fairbanks
9    Arizona     Flagstaff
10   Arizona         Tempe
11   Arizona        Tucson
12  Arkansas   Arkadelphia
13  Arkansas        Conway
14  Arkansas  Fayetteville
15  Arkansas     Jonesboro
16  Arkansas      Magnolia
17  Arkansas    Monticello
18  Arkansas  Russellville
19  Arkansas        Searcy